name: Testing long-reads / singularity (ONT) from PR
on:
  pull_request:
    branches: [ master, dev ]
    types: [ opened, synchronize, reopened ]

jobs:
  run_nextflow:
    name: Run pipeline for the upcoming PR
    runs-on: macos-latest
    
    steps:

      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
      
      - name: Check out pipeline code
        uses: actions/checkout@v2
      
      - name: Install Singularity
        uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.8.3
      
      - name: Install Nextflow
        env:
          CAPSULE_LOG: none
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      
      - name: Clean environment
        run: |
          sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET

      - name: Run tests for long-reads (ont)
        run: |
          nextflow run main.nf -profile singularity,test,lreads,ont
          rm -r work .nextflow*
      
      - name: View results
        run: |
          sudo apt-get install -y tree
          tree lreads_test_ont
